2019-02-27 14:24:19,799 ERROR: Exception on /loan_request [GET] [in c:\python36\scripts\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\scripts\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python36\scripts\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\python-project-2\admin\app\home\views.py", line 81, in loan_request
    return render_template('home/loan_request/loan_requests.html', loan_requests=loan_requests.items, title="Loan Requests", next_url=next_url, prev_url=prev_url)
  File "c:\python36\scripts\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\python36\scripts\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\python-project-2\admin\app\templates\home\loan_request\loan_requests.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\python-project-2\admin\app\templates\base.html", line 58, in top-level template code
    {% block body %}
  File "C:\python-project-2\admin\app\templates\home\loan_request\loan_requests.html", line 13, in block "body"
    {% include 'home/loan_request/loan_request.html' %}
  File "C:\python-project-2\admin\app\templates\home\loan_request\loan_request.html", line 24, in top-level template code
    <a href="{{ url_for('home.get_one_loan_type', loan_type_id=loan_request.loan_type_id) }}" class="btn btn-success">
  File "c:\python36\scripts\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\python36\scripts\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python36\scripts\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\python36\scripts\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'home.get_one_loan_type' with values ['loan_type_id']. Did you mean 'home.delete_loan_type' instead?
2019-02-27 14:28:38,525 INFO: Microblog startup [in C:\python-project-2\admin\app\__init__.py:81]
2019-02-27 14:28:46,366 ERROR: Exception on /loan_type/4 [GET] [in c:\python36\scripts\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\scripts\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python36\scripts\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\python-project-2\admin\app\home\views.py", line 549, in get_one_loan_type
    return render_template('home/loan_type/one_loan_type.html', loan_type=loan_type_data, title="Loan Type")
  File "c:\python36\scripts\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\python36\scripts\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\python36\scripts\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home/loan_type/one_loan_type.html
2019-02-27 14:30:49,462 INFO: Microblog startup [in C:\python-project-2\admin\app\__init__.py:81]
2019-02-27 14:31:11,673 ERROR: Exception on /user/1 [GET] [in c:\python36\scripts\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\scripts\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python36\scripts\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python36\scripts\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\python-project-2\admin\app\home\views.py", line 527, in get_one_user
    return render_template('home/user/one_user.html', users=user_data, title="User")
  File "c:\python36\scripts\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\python36\scripts\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\python36\scripts\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\python36\scripts\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home/user/one_user.html
2019-02-27 14:34:19,339 INFO: Microblog startup [in C:\python-project-2\admin\app\__init__.py:81]
2019-02-27 14:35:58,100 INFO: Microblog startup [in C:\python-project-2\admin\app\__init__.py:81]
2019-03-01 09:30:25,177 INFO: Microblog startup [in C:\python-project-2\admin\app\__init__.py:81]
